### ISSUE TITLE
Incorrect IP registered in Consul for Prometheus Output

### ISSUE THREAD

**Issue by jasonyates-thg** [openconfig/gnmic#105]
I'm running consul and gnmic in docker, across 2 VM's. gnmic is configured to use consul for clustering and register it's prometheus output too, the clustering component works great however as i'm running in docker my listen statement is `:7890` and  `:9804` for the api and prometheus output endpoints, I have to define the `service-address` in the clustering configuration to have the right IP registered in consul. However there's no such config option in the prometheus output section gnmic appears to use the IP of the consul server when registering the prometheus output.

How can I define the service-address for the prometheus output in the same way I can for the clustering?

```
# clustering config
clustering:
  cluster-name: cluster
  instance-name: gnmic01
  service-address: "10.249.1.215"
  targets-watch-timer: 30s
  leader-wait-timer: 60s
  locker:
    type: consul
    address: 10.249.0.250:8500

# Configure outputs
outputs:
  prometheus:
    type: prometheus
    listen: :9804 
    path: /metrics 
    event-processors: 
      - interface-descriptions
    service-registration:
      address: 10.249.0.250:8500
```

**Comment by karimra** [comment]
The Prometheus output uses the address part of the `listen` field to register as a service address in Consul.
If that field is empty, Consul defaults to its own address as a service address.

If you want to register `10.249.1.215` as a service address for the prometheus output you should set listen to `listen: 10.249.1.215:9804`.
The caveat here is that your prometheus output listens only to that address, not to any address in the system.

**Comment by karimra** [comment]
I see, let me look into it

**Comment by karimra** [comment]
@jasonyates-thg can you give v0.30.0 a try?

You can set a service address as below:

```yaml
outputs:
  prometheus:
    type: prometheus
    listen: :9804 
    path: /metrics 
    event-processors: 
      - interface-descriptions
    service-registration:
      address: 10.249.0.250:8500
      service-address: 10.249.1.215
```
It will register `Address=10.249.1.215` and `Port=9804`.
You can also set a port with the address `service-address: 10.249.1.215:9999` if the external port is different from the internal one.
