### ISSUE TITLE
Question: Ability to customise subscriptions with targets loaded via consul

### ISSUE THREAD

**Issue by jasonyates-thg** [openconfig/gnmic#106]
Is it possible to customise the subscriptions applied to targets that are loaded via consul?

E.g. For my Junos devices, I want to subscribe to BGP metrics and Interfaces, but for my Cisco devices I only want to subscribe to interfaces. 

At present, it appears that all devices loaded by consul are automatically configured to subscribe to all subscriptions. Is it possible via tags or otherwise to dynamically select what topics to subscribe a device to?

**Comment by karimra** [comment]
Yes it's possible you can do this by using different service names or use the same service name but different tags for each group of routers, e.g:

```yaml
loader:
  type: consul
  address: x.x.x.x:8500
  # 
  # other fields
  #
  services:
    - name: my-routers-gnmi-server
      tags: 
         - tag1=vendorA
         - tag2=SWVersionA
      # configuration map to apply to target discovered from this service
      config:
        subscriptions:
          - interfaces-sub
          - bgp-sub
    - name: my-routers-gnmi-server
      tags: 
         - tag1=vendorB
         - tag2=SWVersionB
      # configuration map to apply to target discovered from this service
      config:
        subscriptions:
          - interfaces-sub
```
Change the tags to match how the routers are registered, the tags sequence matters.
