### ISSUE TITLE
Processors help needed

### ISSUE THREAD

**Issue by gavmckee80** [openconfig/gnmic#115]
Hi , 

Is it possible to take the source (usually this has the hostname from the GNMI device) and split this into fields that I can write as tags?

Example hostname:
region-location-rack-role-foo-01

I want tags:

region=region
location=location
rack=rack
role=role

**Comment by gavmckee80** [comment]
Also is it possible to take a hostname - and split parts of it into tags 

say

Example hostname:
region-location-rack-role-foo-01

I want tags:

region=region
location=location
rack=rack
role=role

**Comment by karimra** [comment]
You can use the starlark processor:
(not tested)
```yaml
processors:
  # processor name
  split-source-tag:
    # processor type
    event-starlark:   
      source: |
        def apply(*events):
          for e in events:
            source = e.tags["source"]
            items = source.split("-", 5)

            # if the number of items is not 5 skip the event message
            if len(items) != 5:
              continue
            
            e.tags["region"] = items[0]
            e.tags["location"] = items[1]
            e.tags["rack"] = items[2]
            e.tags["role"] = items[3]
            # uncomment the next line to remove `region-location-rack-role-` from source.
            # e.tags["source"] = items[4]
          return events

```
