### ISSUE TITLE
Certificate signed by unknown authority after update to 0.30.0

### ISSUE THREAD

**Issue by Sparc0** [openconfig/gnmic#118]
After i updated to 0.30.0 i'm unable to use the http loader. 
`[http_loader] failed to read targets from HTTP server: Get "https://network-portal.hackernet.se/v1/device2/gnmic": x509: certificate signed by unknown authority`

In my loader config i have skip-verify: true

Solved it by downgrading to 0.29.0 again.

**Comment by karimra** [comment]
The TLS config format changed in 0.30.0, my bad I didn't update the docs for the http loader.
It should be:

```yaml
loader:
  type: http
  tls:
    ca-file: xxx
    cert-file: xxx
    key-file: xxxx
    skip-verify: true
```
