### ISSUE TITLE
gnmic does not expose all data to prometheus output

### ISSUE THREAD

**Issue by mdebord-dlr** [openconfig/gnmic#131]
**gnmic version 0.30.0**

I'm having an issue seeing all data on the [prometheus output](https://gnmic.kmrd.dev/user_guide/outputs/prometheus_output/) on valid gnmi paths. The data shows fine on [file/stdout outputs](https://gnmic.kmrd.dev/user_guide/outputs/file_output/). 

Take this example `gnmic.yml` config: 

```
address: "127.0.0.1"
port: 9339
username: test
password: test
insecure: false
log-file: /tmp/gnmic.log

subscriptions:
  port_state
    paths:
      - "/interfaces/interface[name=Ethernet1/1]/state"
    stream-mode: sample
    sample-interval: 15s
    debug: true

outputs:
  output1:
    type: prometheus
    listen: :9804
    path: /metrics
  output2:
    type: file
    file-type: stdout
    format: string
```

The stdout "output2" displays all the data I expect to see. 

For example, one stat I need to collect is the **oper-status** of the interface, that's what I'm after. It shows fine in the stdout/file based outputs, as shown here: 
```
{
  "source": "127.0.0.1",
  "subscription-name": "port_state",
  "timestamp": 1658259810741575019,
  "time": "2022-07-19T19:43:30.741575019Z",
  "prefix": "interfaces/interface[name=Ethernet1/1]/state",
  "updates": [
    {
      "Path": "oper-status",
      "values": {
        "oper-status": "UP"
      }
    },
    {
      "Path": "type",
      "values": {
        "type": "iana-if-type:ethernetCsmacd"
      }
    }
  ]
}
```

However, the "output1" prometheus output (**[see here for full output on pastebin](https://pastebin.com/yK4xC1nm)**) does not show the metric I need. 

**Another example:** I'm doing the same thing with `/components/component/power-supply/state/output-voltage` gnmi path and it has the same issue. The data shows up fine in the file based / stdout output, but does not show on the prometheus metrics page. 

Since the data is in the stdout output, I think that confirms the gnmi paths are valid and problem lies specifically with the prometheus output type, but I can't figure out if this is actually a problem with the software or I'm just configuring it wrong somehow.

Coincidentally there is hyphens (-) in each of these problematic paths (oper-status, power-supply, output-voltage), and I know there is some behind the scene character conversions for the prometheus output, perhaps it could be related? It may be completely unrelated, but I wanted to mention that regardless.

Perhaps I need to add some custom processing to the output to make it valid for prometheus (example: convert str to numerical values)? If so, please advise on any examples or documentation for this.

Thanks for any help on this.

**Comment by karimra** [comment]
As you said you will need to map the string values you receive to numerical values so that Prometheus ingests them.
You can use the [strings.replace processor](https://gnmic.openconfig.net/user_guide/event_processors/event_strings/#replace)

Here is a processor that fits your example
```yaml
processors:
  # processor name
  sample-processor:
    # processor type
    event-strings:
      value-names:
        - "/interfaces/interface/state/oper-status"
      transforms:
        # strings function name
        - replace:
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
```

The hyphens are not an issue, gNMIc will transform the metric name so that it fits Prometheus naming conventions.

Note that the processor work on messages with `event` format, if you are going to write more processors, I advice you to set the `format` field to `event` under the file output so that you can see the `tags` and `values` as they are passed to the processors.
