### ISSUE TITLE
Custom identifier / hostname possibilities

### ISSUE THREAD

**Issue by andrgras** [openconfig/gnmic#138]
Hello

Is it possible to add some custom identifier for IP? I'm using IP address in targets and for it would easier to recognize destinations with hostnames in telegraf output, something like 10.10.10.11=hostaname1 and 10.10.10.12=hostname2

username: admin
password: admin
insecure: true
log-file: /var/logs/gnmic.log
log-max-size: 5

targets:
  10.10.10.11:57400:
    subscriptions:
      - ip_stats
  10.10.10.12:57400:
    subscriptions:
      - ip_stats

outputs:
  influxdb-output:
    type: influxdb
    url: http://127.0.0.1:8086

**Comment by karimra** [comment]
yes you can set any name as a target key and use the `address` attribute to configure the `addr:port`:


```yaml
username: admin
password: admin
insecure: true
log-file: /var/logs/gnmic.log
log-max-size: 5

targets:
  hostname1:
    address: 10.10.10.11:57400
    subscriptions:
    - ip_stats
  hostname2:
    address: 10.10.10.12:57400
    subscriptions:
    - ip_stats

outputs:
  influxdb-output:
    type: influxdb
    url: http://127.0.0.1:8086/
```
