### ISSUE TITLE
Feature Request: using "/" in the subscription-name

### ISSUE THREAD

**Issue by dpajin** [openconfig/gnmic#14]
It seems that it is not possible to use "/" in the subscription names. 
If I configure something like this:
```
subscriptions:  # container for subscriptions
  /system/state:
    paths:
       - "/system/state/hostname"
       - "/system/state/boot-time"
    stream-mode: sample
    sample-interval: 10s
```
this fails with the following error in the logs:
```
2022/11/25 15:23:37.160529 [gnmic] failed to subscribe: missing path(s) in subscription ''
```
