### ISSUE TITLE
Registering a target from a second consul service group deletes all other targets

### ISSUE THREAD

**Issue by jasonyates-thg** [openconfig/gnmic#147]
I have two consul loader service groups setup with different subscriptions and configuration. If I register a device in the second group, gnmic deletes all devices from the first group and only monitors the new device.

```
loader:
  type: consul
  datacenter: lon
  address: 10.249.0.250:8500
  enable-metrics: true
  services:
    - name: junos-targets
      subscriptions:
        - interfaces
        - junos-bgp
    - name: cumulus-targets
      config:
        encoding: JSON
        skip-verify: true
      subscriptions:
        - interfaces
 ```

I have 30+ devices in the `junos-targets` group working correctly. If I add a device to `cumulus-targets` the logs show all the junos-targets being deleted despite them still being active in Consul. If I restart gnmic, it registers devices from both services.

```
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router1 HTTP/1.1" 404 57
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router2 HTTP/1.1" 404 59
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router3 HTTP/1.1" 404 59
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router4 HTTP/1.1" 404 51
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router5 HTTP/1.1" 404 59
10.249.0.250 - - [15/Jun/2023:15:48:22 +0000] "DELETE /api/v1/config/targets/router6 HTTP/1.1" 404 58
2023/06/15 15:48:22.735425 [gnmic] adding target {"name":"cumulus-test01","address":"10.12.128.55:9339","username":"","password":"****","timeout":10000000000,"insecure":true,"skip-verify":true,"buffer-size":100,"retry-timer":10000000000,"log-tls-secret":false,"gzip":false,"token":""}
```
