### ISSUE TITLE
Running mix of Sample & On_Change streams

### ISSUE THREAD

**Issue by dbhatia16** [openconfig/gnmic#194]
Currently we can run both sample and on_change subscriptions through a single config file either on one or multiple targets.
But this acts as two different subscriptions one sample and other on_change.
I want to run mix of sample and on_change through one stream. Is it possible through gnmic?

**Comment by karimra** [comment]
Thanks for pointing this out. Right now, there's no straight-up way to do this through the CLI. You can do it with a bit of Go code.
I was thinking about making it possible via the CLI, but there was no demand before.

**Comment by karimra** [comment]
With v0.31.7 you can define a mix of sample and on-change stream subscriptions in the same subscribe request:

```yaml
subscriptions:
  sub1:
    mode: stream # this is the default value for mode
    stream-subscriptions:
      - paths:
           - /interface/oper-state
        stream-mode: on-change
      - paths:
           - /interface/statistics
        stream-mode: sample
        sample-interval: 10s
```
