### ISSUE TITLE
Ability to specify outputs per-subscription

### ISSUE THREAD

**Issue by mwdomino** [openconfig/gnmic#198]
Is it possible to specify which outputs a specific subscription should be sent to? If not, I'd be interested in opening a feature request for this behavior.

For example:
```
subscriptions:
  interface_status:
    paths: 'some/path/here'
    outputs:
      - nats
      - prometheus

  bgp_neighbor_state:
    paths: 'some/other/path'
    outputs:
      - nats
 
outputs:
  nats:
  prometheus:
```

I'd like to be able to specify that only certain subscriptions are forwarded to our Prometheus instance while other (or all) events go to a NATS instance. 

I've attempted to use `processors` to only allow certain events but was unable to determine which specific filter options to use. `processors` may be the solution, but I'm unsure of how to view the messages in a raw form so that I could properly match a regex to tags/values/etc. When running `gnmic get --path 'the/path'` I did not see any tags or other data returned, only the `updates` field and timestamps/metadata.

Thanks for your assistance and let me know if I can provide any more info. I'm also happy to contribute code with some direction if that's what is needed.

**Comment by karimra** [comment]
As you said, it's possible using processors.
Processors apply to outputs using the `event` format.

The [`event-allow`](https://gnmic.openconfig.net/user_guide/event_processors/event_allow/) and [`event-drop`](https://gnmic.openconfig.net/user_guide/event_processors/event_drop/) processors can be used to allow or filter out messages per output.

```yaml
processors:
  output1-filter:
    event-allow:
      condition: .tags["subscription-name"] == "sub1"
 ```
 
 By adding the above processor to the prometheus output:
 ```yaml
 outputs:
   prometheus:
     type: prometheus
     event-processors:
       - output1-filter
 ```
 
 Only the updates from the subscription `sub1` will be available through the prometheus output.
 You can apply the same (opposite) logic using the `event-drop` processor
 
 Both the `event-drop` and `event-allow` processors logic can be defined using regexes as well.
 But the `condition` field (a JQ expression) is more flexible since it allows to combine multiple fields to evaluate a single condition.
 
 To view messages in the event format, you have to add the flag `--format event` when using the cli (It works with get and subscribe cmds but I would recommend using the subscribe command for your tests)
 
 The Prometheus output uses the `event` format by default, so no extra config is required for the processors to apply. 
 If you want to use processors under the nats output you have to set the `format` attribute to `event`:
 ```yaml
 outputs:
   nats:
     type: nats
      format: event
 ```
 
 All that being said, I wouldn't be against adding an `allowed-subscriptions` field under all the outputs to explicitly filter out unwanted subscriptions. It will be easier to understand and configure for users and it would apply to all formats.
