### ISSUE TITLE
Question: Clarification on the --backoff Flag Behavior in gNMIC Subscription Service

### ISSUE THREAD

**Issue by wendall-robinson** [openconfig/gnmic#204]
`--backoff` [description link](https://gnmic.openconfig.net/cmd/subscribe/#backoff)

I hope this finds you well. I am writing to seek clarification on the behavior of the `--backoff` flag in the gNMIC Subscription service.

Based on the existing documentation, the behavior of the `--backoff` flag is somewhat ambiguous to me. Could you please confirm how it operates in the context of multiple switches and subscriptions? Specifically, I am trying to understand if:
1. The backoff value delays the subscription request to each subscription across all switches, meaning both switchA and switchB would receive the first subscription request, and then gNMIC would wait to send the next subscription request equal to the time set in the backoff value (Option A).

2. The backoff value delays the subscription request to each switch, meaning all subscription requests would be sent to switchA, and then gNMIC would wait for the backoff duration before sending all subscription requests to switchB (Option B).

3. Something else, neither Option A or B.

Also, I use a `gnmic.yml` file to configure our `gNMIC` service, here is an example snippet of our configuration:
```yaml
subscriptions:
  interface_status:
    paths:
      - "interfaces/interface/state/oper-status"
    mode: stream
    stream-mode: ON_CHANGE
    backoff: 5s
    output: output1

ethernet_state:
    paths:
      - "/interfaces/interface/ethernet/state"
    mode: stream
    stream-mode: ON_CHANGE
    backoff: 5s
    output: output1
```

Thank you in advance for your assistance.
