### ISSUE TITLE
Is it possible to run gnmic as gnmi-server without a subscription

### ISSUE THREAD

**Issue by arnaudcoquelet** [openconfig/gnmic#205]
I'm new to gnmic, so maybe I'm missing something,
But I'm curious if there is a way to start gnmic as a gnmi-server so it behaves as a proxy for SET/GET operations, but without defining a subscription.

Right now the only I get it to work is if I define  a subscription and start it like this "gnmic --config config.yml subscribe"

Here is how the config.yml is built:
```
# cat config.yml 
username: admin
password: NokiaSrl1!
skip-verify: true
encoding: json_ietf
log: true

gnmi-server:
  address: 0.0.0.0:57400
  log: true
  enable-metrics: true

api-server:
  enable-metrics: true

targets:
  spine1:
    address: 10.96.8.70:50052
  spine2:
    address: 10.96.8.67:50052
  leaf1:
    address: 10.96.8.68:50052
  leaf2:
    address: 10.96.8.69:50052
  leaf3:
    address: 10.96.8.72:50052

subscriptions:
  sub1:
    paths:
      - /system/name
    stream-mode: sample
    sample-interval: 60s
```

If the subscriptions is not defined, the application stops as expected because gnmic was started with the keyword **subscribe**.
