### ISSUE TITLE
Are wild cards actually supported in gNMIc?

### ISSUE THREAD

**Issue by fishdrummer** [openconfig/gnmic#206]
Hi,

I'm trying to use wild cards but as far as I can see, it is not supported in gNMIc:

- in CLI (prompt) mode:
```
gnmic> get --path /interfaces/interface[name=*]/state/ 
target "X.X.X.X" get request failed: "X.X.X.X:50051" GetRequest failed: rpc error: code = Internal desc = descr:data translation error [error:translation-unmapped msg:List object /filter/interfaces/interface/interface is unmapped path:/interfaces/interface]
```

- in collector mode (with a Prometheus output), nothing is scraped:
````
subscriptions:
  # Add subscriptions configuration here
  # e.g:
  sub1:
    paths:
      - /interfaces/interface[name=*]/state/
    stream-mode: sample
    sample-interval: 30s
````

I would like to use explicit wild cards instead of an implicit one so that formatting prometheus metrics/labels is easier (ie interface name appears immediately in the metric name).

Thanks!
