### ISSUE TITLE
Advice using JQ to generate a set of tags

### ISSUE THREAD

**Issue by gavmckee80** [openconfig/gnmic#224]
Would it be possible to get an example using JQ to generate some tags on data?

I want to add a set of tags
site
location
rack
environment

Can I use JQ to do this by splitting the source and (say source was split into a variable temp using the delimiter - )
site = temp[0]
location = temp[1]
rack = temp[2]
environment = temp[3]

```
{
  "source": "ndcr-wwh01-r03-lab-eth-leaf-03:9339",
  "subscription-name": "default-1694535492",
  "timestamp": 1688401959982301894,
  "time": "2023-07-03T09:32:39.982301894-07:00",
  "prefix": "interfaces/interface[name=swp14]",
  "target": "netq",
  "updates": [
    {
      "Path": "state/admin-status",
      "values": {
        "state/admin-status": "DOWN"
      }
    }
  ]
}
```

THanks

**Comment by peejaychilds** [comment]
I didn't test it ... something like this?

`processors:
 proc-tag-source:
   event-starlark:
     source: |
       def apply(*events):
         for e in events:
           mylist = e.source.split("-")
             e.tags['site']=mylist[0]
             e.tags['location']=mylist[1]
             e.tags['rack']=mylist[2]
             e.tags['environment']=mylist[3]
         return events`

**Comment by karimra** [comment]
The message the processor applies on should be an event, you get that by adding `--format event` to the command that got you this response.
```json
{
  "source": "ndcr-wwh01-r03-lab-eth-leaf-03:9339",
  "subscription-name": "default-1694535492",
  "timestamp": 1688401959982301894,
  "time": "2023-07-03T09:32:39.982301894-07:00",
  "prefix": "interfaces/interface[name=swp14]",
  "target": "netq",
  "updates": [
    {
      "Path": "state/admin-status",
      "values": {
        "state/admin-status": "DOWN"
      }
    }
  ]
}
```

You can use starlark as mentioned above, just make sure to select the `source` fields from under the tags.
If you want to use jq, you can do something like this:

```yaml
 proc-tag-source:
   event-jq:
     expression: |
       .tags.source as $source
       | .tags += (
             $source | split("-") | .[0:4] | {
             "site": .[0],
             "location": .[1],
             "rack": .[2],
             "environment": .[3]
             }
          )
```
