### ISSUE TITLE
loader with subscription mode poll 

### ISSUE THREAD

**Issue by nitzan-tz** [openconfig/gnmic#236]
If I have the poll mode in the subscription configuration it cant load the targets from a file with the following error 

`gnmic-1    | Error: failed reading targets config: failed reading targets config: no targets found
`
The relevant configuration is 
```
loader:
  type: file
  # path to the file
  path: /app/targets.yaml
  # watch interval at which the file
  # is read again to determine if a target was added or deleted.
  interval: 300s
  # if true, registers fileLoader prometheus metrics with the provided
  # prometheus registry
  enable-metrics: false


subscriptions:
  show_version:
    paths:
      - "cli:/show version"
    mode: POLL
    stream-mode: sample
    sample-interval: 30s
    encoding: json
```

If I am using a different subscription in mode stream it load the targets correctly
```
  optics_dom:
    paths:
      - "components/component/transceiver/physical-channels/channel/state/"
    stream-mode: sample
    sample-interval: 300s
    mode: STREAM

```
