### ISSUE TITLE
InfluxDB - data is not sent to output

### ISSUE THREAD

**Issue by LDTips** [openconfig/gnmic#241]
It looks like the gNMIc is not sending any data to the InfluxDB endpoint. The health check requests are being made, but the subscription data fetched from the router is not sent.

Using the following configuration, based on the documentation:

```yaml
address: <ROUTER_IP:PORT>
username: <USER>
password: <PASS>
insecure: true
debug : true


subscriptions:
  port_stats:
    paths:    
      - <YANG_PATH>
    stream-mode: sample
    sample-interval: 10s
    encoding: proto

outputs:
  output1:
    type: influxdb 
    url: <INFLUXDB_IP:PORT>
    org: <ORG_NAME>
    bucket: <BUCKET_NAME>
    token: <TOKEN>
    batch-size: 10
    flush-timer: 10s
    use-gzip: false
    enable-tls: false
    tls:
      ca-file:
      cert-file:
      key-file:
      skip-verify: true
    override-timestamps: false 
    timestamp-precision: ns
    health-check-period: 30s 
    debug: true 
    add-target: 
    target-template:
    enable-metrics: false 
    event-processors: []
    cache:
      expiration: 0s
      debug: true
    cache-flush-timer: 5s
```

 
The debug shows "response missing target". The Telemetry data is received from the router, but then it is not sent.
Below is the log:
[gNMIc_debug.log](https://github.com/openconfig/gnmic/files/12831538/gNMIc_debug.log)

To rule out the issues with the InfluxDB, I did sanity checks related to pinging the IP, port being open etc.
Furthermore, using the InfluxDB python module I managed to manually push and fetch some data to and from the org and bucket that are used in the config (redacted for security purposes).
