### ISSUE TITLE
Consul Loader ignoring tags

### ISSUE THREAD

**Issue by lucabrasi83** [openconfig/gnmic#272]
Hi!

I'm using gnmic v0.33 and have setup the Consul loader as below with multiple entries using the same name but different tags in order to apply different subscriptions:

 

```yaml

loader:
  type: consul
  address: consul:8500
  datacenter: dc1
  enable-metrics: true
  services:
    - name: networks-gnmic-targets
      tags:
        - "vendor=arista"
        - "platform=eos"
      config:
        subscriptions:
          - netgenie_telemetry_proto
        outputs:
          - prom-output-proto
        insecure: true
    - name: networks-gnmic-targets
      tags:
        - "vendor=cisco"
        - "platform=iosxe"
      config:
        subscriptions:
          - netgenie_telemetry_json
        outputs:
          - prom-output-cisco-xe
        insecure: true

```

The tags are correctly assigned to the target service ID's in Consul:

 

```json

{

  "ID": "test-cat9k",
  "Service": "networks-gnmic-targets",
  "Tags": [
    "vendor=cisco",
    "platform=iosxe"

  ],

  "Meta": {},
  "Port": 50052,
  "Address": "10.0.46.11",
  "Weights": {
    "Passing": 1,
    "Warning": 1
  },

  "EnableTagOverride": false,
  "ContentHash": "fe321e05900eb3a8"

}

```

However, this seems to be ignored by gnmic as it just applies the config from the first service name:

 

`2023/11/01 23:20:58.784037 [gnmic] adding target {"name":"test-cat9k","address":"[10.0.46.11:50052](http://10.0.46.11:50052/)","username":"****","password":"****","timeout":10000000000,"insecure":true,"skip-verify":false,"subscriptions":["netgenie_telemetry_proto"],"outputs":["prom-output-proto"],"buffer-size":100,"retry-timer":10000000000,"log-tls-secret":false,"gzip":true,"token":""}`

 

Is it the correct way I'm configuring it and it's supposed to work ?
