### ISSUE TITLE
Can't get Kafka metrics on Prometheus server

### ISSUE THREAD

**Issue by tomasrojas26** [openconfig/gnmic#303]
Hello! I'm running gNMIc as a server ([Listen](https://gnmic.openconfig.net/cmd/listen/)) with this command line:
```bash
gnmic listen --config /gnmic-config.yaml --prometheus-address :9805
```
This is the Kafka Output configuration:
```yaml
  kafka:
    type: kafka
    address: (my bootstrap servers)
    topic: (my topic)
    enable-metrics: true
```
According to the [documentation](https://gnmic.openconfig.net/user_guide/outputs/kafka_output/#kafka-output-metrics), the kafka output metrics are exposed when a prometheus server is enabled, but it's not my case.
By the way, my prometheus endpoint works fine, exposing the grpc metrics, memory and other useful data, but I can't get Kafka Output metrics.
I read this issue #175 and the only difference is that they expose the metrics through 7890 port (API Rest), which I can't get running for some reason, I think the API can't be configured in a server mode.

Thank you in advance for your help.
