### ISSUE TITLE
Processor event-allow with value-names does not work

### ISSUE THREAD

**Issue by LDTips** [openconfig/gnmic#316]
When learning about processors in gNMIc, I noticed the event-allow processor for value-names does not work. It simply does not perform the filtering. According to the documentation, the only key-value pairs should be the ones where key matches the provided regex. However, the filtering does not happen at all.

Consider the following config
```yaml
# gNMI target address; CLI flag `--address`
address: REDACTED
# gNMI target user name; CLI flag `--username`
username: REDACTED
# gNMI target user password; CLI flag `--password`
password: REDACTED
# Port
# connection mode; CLI flag `--insecure`
insecure: true
# Skip SSL certificate verification
#skip-verify: true
# log file location; CLI flag `--log-file`
# Enable or disable debugging
debug : false
# Subscription for statistics on a port
subscriptions:  # container for subscriptions
  port_stats:     # a named subscription, a key is a name
    paths:      # list of subscription paths for that named subscription
      - "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/vrfs/vrf/afs/af/safs/saf/ip-rib-route-table-names/ip-rib-route-table-name/routes/route"
    stream-mode: sample # one of [on-change target-defined sample]
    sample-interval: 10s
    encoding: json
    outputs:
      - 'output1'

processors:
  proc1:
    event-allow:
      value-names:
        - ".*edm"

outputs:
  output1:
    # required
    type: file 
    # filename to write telemetry data to.
    # will be ignored if `file-type` is set
    filename: 
    # file-type, stdout or stderr.
    # overwrites `filename`
    file-type: stdout
    # string, message formatting, json, protojson, prototext, event
    format: event
    # string, one of `overwrite`, `if-not-present`, ``
    # This field allows populating/changing the value of Prefix.Target in the received message.
    # if set to ``, nothing changes 
    # if set to `overwrite`, the target value is overwritten using the template configured under `target-template`
    # if set to `if-not-present`, the target value is populated only if it is empty, still using the `target-template`
    add-target: 
    # string, a GoTemplate that allow for the customization of the target field in Prefix.Target.
    # it applies only if the previous field `add-target` is not empty.
    # if left empty, it defaults to:
    # {{- if index . "subscription-target" -}}
    # {{ index . "subscription-target" }}
    # {{- else -}}
    # {{ index . "source" | host }}
    # {{- end -}}`
    # which will set the target to the value configured under `subscription.$subscription-name.target` if any,
    # otherwise it will set it to the target name stripped of the port number (if present)
    target-template:
    # boolean, valid only if format is `event`.
    # if true, arrays of events are split and marshaled as JSON objects instead of an array of dicts.
    split-events: false
    # string, a GoTemplate that is executed using the received gNMI message as input.
    # the template execution is the last step before the data is written to the file,
    # First the received message is formatted according to the `format` field above, then the `event-processors` are applied if any
    # then finally the msg-template is executed.
    msg-template:
    # boolean, if true the message timestamp is changed to current time
    override-timestamps: 
    # boolean, format the output in indented form with every element on a new line.
    multiline: 
    # string, indent specifies the set of indentation characters to use in a multiline formatted output
    indent: 
    # string, separator is the set of characters to write between messages, defaults to new line
    separator: 
    # integer, specifies the maximum number of allowed concurrent file writes
    concurrency-limit: 1000 
     # boolean, enables the collection and export (via prometheus) of output specific metrics
    enable-metrics: false
     # list of processors to apply on the message before writing
    event-processors:
      - 'proc1'
```

I expect only values that contain edm in their key to be present in the output, but instead every value is present. Simply - the filtering does not occur at all.
I am using the latest gNMIc version
version : 0.34.3
 commit : d461fa9
   date : 2023-11-14T02:13:11Z
 gitURL : https://github.com/openconfig/gnmic
   docs : https://gnmic.openconfig.net
