### ISSUE TITLE
[bug] failed initializing event processor - event processor not found

### ISSUE THREAD

**Issue by gmrmn** [openconfig/gnmic#326]
Hello! 
I am trying to use `event-combine` processor, but it fails to find any of its sub-processors. 
Sample:
```yaml
processors:
  timestamper:
    event-override-ts:
      precision: ns
  test-pipeline:
    event-combine:
      processors:
        - condition: '.tags["subscription-name"] == "any"'
          name: timestamper
```
Logs:
```
[gnmic] failed to init output type "prometheus": failed initializing event processor 'test-pipeline' of type='event-combine': "timestamper" event processor not found
```

I suspect the problem is somewhere [here](https://github.com/openconfig/gnmic/blob/0bba558313591abd2c4f080070fc0659bbf05d5e/pkg/formatters/event_combine/event_combine.go#L113) - it looks like an error is always returns, whenever an `event-combine` processor [is initialized](https://github.com/openconfig/gnmic/blob/0bba558313591abd2c4f080070fc0659bbf05d5e/pkg/formatters/processors.go#L157C5-L161C6). 

Also it looks like this "broken" processor kinda breaks the entire `output`. I use prometheus and I see neither metrics nor logs of other processors, but the app does't stop and as for me thats a little confusing.

P.S. [Bonus question] Since I am unable to check the event-combine processor, its condition logic is not yet crystal clear for me. My purpose is to "assign" a batch of processors to concrete subscription. Can I do that w/o adding the same condition statement to every sub-processor, but only declare it for the first one?
```yaml
processors:
  # other 
  pipeline:
     event-combine:
        - name: proc1
          condition: 'my_condition'
        - name: proc2  # this one will only be invoked if `my_condition` is true?
                                 # OR since here is no condition every event matches here?
```

P.P.S Thank you for the awesome project and great docs!  We are actively working on integration of gNMIc into our monitoring process of several DCs.
