### ISSUE TITLE
Question configuration example for clustering Kubernetes/redis locker?

### ISSUE THREAD

**Issue by pboers1988** [openconfig/gnmic#344]
In the documentation I can only find details about how to setup consul as a clustering locker. I was wondering if there are some working examples of how to setup Kubernetes as locker in the clustering configuration. I see there is code in the repository to support it, however there are no good examples in the tests or in the docs about how to configure it. The same can be said about redis. Does anyone have some pointers towards how to setup these lockers? Or is consul still the only locker that "really works"?

I would prefer to be able to use Kubernetes or redis as they are already part of the infrastructure that we are running.

Thanks!

**Comment by hellt** [comment]
I think there are no docs specifically about the k8s locker option.
Maybe you can get what you need from the comments in the PR that added this capability https://github.com/karimra/gnmic/issues/560#issuecomment-1099762889

(or maybe wait till @karimra comes back online)

**Comment by karimra** [comment]
There are no dedicated doc pages for those two lockers, that needs to be added.

Meanwhile here is a short explanation of the config options with their defaults:
- kubernetes locker
```yaml
clustering:
  # 
  locker:
    type: k8s
    # namespace where the leases will be created
    namespace: default
    # lease-duration, defines the duration of a lease
    lease-duration: 10s
    # defines how often leases are renewed.
    # If the set values is eq or higher than the `lease-duration`, lease-duration/2 applies.
    # Otherwise the set value applies.
    renew-period: 
    # defines a simple backoff duration in case of errors
    retry-timer: 2s
    # enable extra logging
    debug: false
```

- redis locker:
```yaml
clustering:
  # 
  locker:
    type: redis
    # single address or a seed list of host:port addresses of cluster/sentinel nodes.
    # if more than one address is set, the locker uses a redis cluster client.
    servers:
      - 
    # specifies a master name to create a sentinel backed redis FailoverClient
    master-name:
    # a password that should match `requirepass` in redis server config (Redis 5.0 or lower)
    # or the user password (Redis 6.0 or higher)
    password:
    # sets the expiration time of a Redis mutex
    lease-duration: 10s
    # defines the frequency of Redis mutex expiration refresh.
    # If the set values is eq or higher than the `lease-duration`, lease-duration/2 applies.
    # Otherwise the set value applies.
    renew-period: 
    # defines a simple backoff duration in case of errors.
    retry-timer: 2s
    # poll timer of registered Redis services.
    poll-timer: 10s
    # enable extra logging
    debug: false
```

When writing this I realized that the redis locker could use some updates to add some extra config options.
