### ISSUE TITLE
JQ filtering inconsistency?

### ISSUE THREAD

**Issue by LDTips** [openconfig/gnmic#379]
When designing a JQ filter, I wanted to make it apply only on some given condition. I used condition keyword. However, it has a bit different behavior than the expression itself. The condition is by default applied at the level of the array rather than at root. This configuration snippet is an example:

```yaml    
processors:
  proc1:
     event-jq:
       condition: has("values")
       expression: .[].values |= with_entries(select(.key | test("route/protocol-name|route/prefix$|route/prefix-length-xr|interface-name")))
```

In the expression I need to specify `.[]`, but for the condition I just need to write `has("values")` rather than `.[] | has("values")`. Same as I expected `any(has("values"))` to work, but it doesn't. Is this a design choice? Wouldn't this cause some issues for more advanced cases where the array has more than one element?
