### ISSUE TITLE
Target-specific options aren't updated when loaded dynamically

### ISSUE THREAD

**Issue by jhujhiti** [openconfig/gnmic#39]
I'm not sure if this is a bug or intended behavior, but I noticed that loaded targets (at least for the file loader) aren't having their target-specific options updated. For example, if I have a target file whose contents are

```yaml
targeta:
  address: 192.0.2.1:1234
  username: gnmic
  password: secret
  timeout: 2s
  skip-verify: true
```

and whose subscriptions are up and working, a change to the options there will be logged by the loader but never acted upon. I've tested this with the address, username, and password options. I would expect that the subscriptions to the target would be restarted with the new options. (At least where the change would require a new session.)

The updates don't seem to make it into the target configuration at all, because even after closing the connection from the other end and letting gNMIc reconnect, it still connects with the original values. Removing the target entirely, reloading the file, and adding the target back with the new values does work.
