### ISSUE TITLE
Environment expansion does not always work

### ISSUE THREAD

**Issue by mathieudevos** [openconfig/gnmic#458]
Hey,

As the title states, if you attempt to use environment variable expansion through `${ENV_VAR}` it does not seem to work on top level.

Example of gnmic.yml file:

```
encoding: json_ietf
log: true
address: ${MY_ADDRESS}
token: ${MY_TOKEN}

subscriptions:
  SWITCH1:
    paths:
      - openconfig:interfaces/interface/config/description
    target: SWITCH1SERIAL
    outputs:
      - influx-output

outputs:
  influx-output:
    type: influxdb
    url: ${INFLUX_ADDRESS}
    token: ${INFLUX_TOKEN}
```

^ in the above example, INFLUX_ADDRESS and INFLUX_TOKEN will be replaced by their respective env vars, however ${MY_ADDRESS} and ${MY_TOKEN} will not be substituted and be dropped as is. 

Figuring this out took me quite a while as I was seeing unauthorized issues with a token that I was quite sure *should* work.

Hopefully this either gets amended in the information or bugfixed.
