### ISSUE TITLE
Docker compose container not accepting valid command string

### ISSUE THREAD

**Issue by adietrich-ussignal** [openconfig/gnmic#47]
Using the docker-compose container, the command to kick-off a subscription appears to be invalid causing the container to fail. 

Running the same command ad-hoc with gnmic outside of a container works as expected.

```
 gnmic:
    container_name: gnmic
    image: gnmic/gnmic:latest
    ports: 
      - 9804:9804
    volumes: 
      - '/etc/gnmic/gnmic.yaml:/app/gnmic.yaml'
    command: 
      - "subscribe --config /app/gnmic.yaml"
    restart: always
```

Docker log output:
```
Error: unknown command "subscribe --config /app/gnmic.yaml" for "gnmic"
Run 'gnmic --help' for usage.
```
