### ISSUE TITLE
Performance optimisation for prometheus output

### ISSUE THREAD

**Issue by aned** [openconfig/gnmic#498]
I'm testing this config file https://gist.github.com/aned/8b68e77791dc3bb9eeda903ce54e1643
After adding ~30 targets, I'm seeing some pretty heavy load on the server. 
Are there any obvious improvements I can make in the config? 

In this section 
```
  lldp:
    paths:
       - "/lldp/interfaces/interface/neighbors/neighbor/state/system-name"
       - "/lldp/interfaces/interface/neighbors/neighbor/state/port-id"
    stream-mode: sample
    sample-interval: 30s
    heartbeat-interval: 30s
    updates-only: false
```
I'm caching lldp, it doesn't change much so need to do 30s updates, would it break things if `sample-interval` is set to like `1h` or it needs to be done via cache expiration?

**Comment by karimra** [comment]
I see you went all out with the processors :)

The first obvious change I would make is moving the `drop-metrics` up in the list of processors under the output. If the event messages are going to be dropped they don't need to travel down the pipeline of processors. Unless you are using them to enrich other values (I didn't see that in the starlark processors)

As for the lldp subscription, If it's not going to change much, use an on-change subscription (if the router supports it)

```yaml
  lldp:
    paths:
       - "/lldp/interfaces/interface/neighbors/neighbor/state/system-name"
       - "/lldp/interfaces/interface/neighbors/neighbor/state/port-id"
    stream-mode: on-change
```

How much of a heavy load are we talking about ? I see you enabled the api-server metrics and you have a Prometheus server.
```yaml
api-server:
  address: :7890
  enable-metrics: true
```
Do you have a target definition for `gnmic:7890/metrics` ? We will be able to see how much (and what) is being used.

A few more optimisations:

1)
This processor matches ALL your events, and runs the `old` regex on all of their values.
```yaml
  rename-metrics:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "name"
            old: "interfaces/interface/.*/description"
            new: "ifAlias"
  ```
  
  If you know exactly what you are going to replace, set it in the matching section not in the transform
  
  ```yaml
  rename-metrics:
    event-strings:
      value-names:
        - "interfaces/interface/.*/description"
      transforms:
        - replace:
            apply-on: "name"
            old: "interfaces/interface/.*/description"
            new: "ifAlias"
  ```
  
  2)
  
  Same for this processor. 

  ```yaml
  rename-metrics-arista-ngbb:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "name"
            old: ".*connectivityMonitor/status/hostStatus/.*/defaultStats/packetLoss"
            new: "PacketLossAristaXBR"
        - replace:
            apply-on: "name"
            old: ".*connectivityMonitor/status/hostStatus/.*/defaultStats/latency"
            new: "LatencyAristaXBR"
        - replace:
            apply-on: "name"
            old: ".*connectivityMonitor/status/hostStatus/.*/defaultStats/jitter"
            new: "JitterAristaXBR"
        - replace:
            apply-on: "name"
            old: ".*meminfo/memTotal"
            new: "MemTotalAristaXBR"
        - replace:
            apply-on: "name"
            old: ".*meminfo/memAvailable"
            new: "MemAvailableAristaXBR"
        - replace:
            apply-on: "name"
            old: "/queues/queue"
            new: "_queue"
        - trim-prefix:
            apply-on: "name"
            prefix: "/interfaces"
        - trim-prefix:
            apply-on: "name"
            prefix: "/qos/interfaces"
  ```
All these transforms are independent from each other.
The transforms in a single `event-strings` processor **are applied the all the event messages in sequence**.
So I would create separate processors for each one.

3)

In this processor, the old tags are well known
```yaml
rename-labels-interface:
  event-strings:
    tag-names:
      - ".*"
    transforms:
      - replace:
          apply-on: "name"
          old: "source"
          new: "alias"
      - replace:
          apply-on: "name"
          old: "interface_name"
          new: "ifName"
      - replace:
          apply-on: "name"
          old: ".*interface-id"
          new: "ifName"
  ```
  I would place them in the `tag-names` field or even create a processor for each one.
  
  ```yaml
rename-labels-interface:
    event-strings:
      tag-names:
        - "source"
        - "interface_name"
        - .*interface-id"
      transforms:
        - replace:
            apply-on: "name"
            old: "source"
            new: "alias"
        - replace:
            apply-on: "name"
            old: "interface_name"
            new: "ifName"
        - replace:
            apply-on: "name"
            old: ".*interface-id"
            new: "ifName"
  ```
  
  There are a couple more processors like this, I think you get the idea. you can save a lot by skipping a few regex evaluations  (over 30 routers).
