### ISSUE TITLE
Trying to understand the use of models in subscriptions

### ISSUE THREAD

**Issue by Sparc0** [openconfig/gnmic#530]
Trying to understand what the benefits is of adding models under a subscription.
I have subs one using models and one is not and the result seems to be the same. 
I read this and made it little what they can be used for https://openconfig.net/docs/gnmi/gnmi-specification/#26-schema-definition-models 

- Whats the correct way of using them? 
- Is there any performance benefits when using them? 

I have tried to look into e.g https://openconfig.net/projects/models/schemadocs/jstree/openconfig-interfaces.html#
And the path i get there for counters is not working. 
```/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters``` Not working
```/interfaces/interface/state/counters``` Working 

One of many gnmic examples
```
interface_state_with:                                        
  paths:                                                 
    - "openconfig-interfaces:/interfaces"                
  models:                                                
    - "openconfig-interfaces"                            
  mode: stream                                           
  stream-mode: sample                                    
  sample-interval: 15s                                   
  heartbeat-interval: 15s                                
  encoding: proto                                        
interface_state_without:                                        
  paths:                                                 
    - "/interfaces"                                      
  mode: stream                                           
  stream-mode: sample                                    
  sample-interval: 15s                                        
  heartbeat-interval: 15s                                
  encoding: proto                                        
```
