### ISSUE TITLE
Un defined event-processors in prometheus output

### ISSUE THREAD

**Issue by nitzan-tz** [openconfig/gnmic#560]
Hi,

On GNMIC 0.39.1 if I have prometheus (Maybe also other types of outputs ) and on the event-processors list there is event-processor that is not defined under processors: prometheus  doesnt listen on the port and in debug I can see
[prometheus_output:prom-all-output] writing expired after 0s

It will be good that it will ignore the missing processor or rise an error in that case 

For example in the below config 
      - delete-bng-processor
      - replace-bng-processor
 Are not defined 

```
processors:
################ bgp #################
  delete-bgp-processor:
    event-delete:
      value-names:
        - "messages.*"
        - "import.*"
  replace-bgp-processor:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "name"
            old: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state"
            new: "bgp_neighbor_afti_safi"
        - replace:
            apply-on: "name"
            old: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state"
            new: "bgp_neighbor"
        - replace:
            apply-on: "name"
            old: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/state"
            new: "bgp_peer_group_afi_safi"
        - replace:
            apply-on: "name"
            old: "/network-instances/network-instance/protocols/protocol/bgp"
            new: "bgp"

outputs:
  prom-all-output:
    type: prometheus
    strings-as-labels: true
    listen: "127.0.0.1:9291"
    event-processors:
      - delete-bng-processor
      - replace-bng-processor
      - delete-bgp-processor
      - replace-bgp-processor
```
