### ISSUE TITLE
Event parsing misbehavior

### ISSUE THREAD

**Issue by bondar-aleksandr** [openconfig/gnmic#584]
Hi team,

I'm trying to subscribe to "rfc7951:/Cisco-IOS-XE-interfaces-oper:interfaces/interface/oper-status", but the interface name is not specified as tag in output. I get something like this:
```
{
	"source": "coresw",
	"subscription-name": "intf-config",
	"timestamp": 1737390688430774000,
	"time": "2025-01-20T16:31:28.430774Z",
	"updates": [
		{
			"Path": "rfc7951:Cisco-IOS-XE-interfaces-oper:interfaces/interface[name=AppGigabitEthernet1/0/1]/ipv4",
			"values": {
				"Cisco-IOS-XE-interfaces-oper:interfaces/interface/ipv4": "0.0.0.0"
			}
		},
		{
			"Path": "rfc7951:Cisco-IOS-XE-interfaces-oper:interfaces/interface[name=GigabitEthernet0/0]/ipv4",
			"values": {
				"Cisco-IOS-XE-interfaces-oper:interfaces/interface/ipv4": "0.0.0.0"
			}
		},
		{
			"Path": "rfc7951:Cisco-IOS-XE-interfaces-oper:interfaces/interface[name=GigabitEthernet1/0/1]/ipv4",
			"values": {
				"Cisco-IOS-XE-interfaces-oper:interfaces/interface/ipv4": "0.0.0.0"
			}
		}
	]
}
```
Config file is as follow:
```
targets:
  wmg-coresw:
    address: 172.18.59.1:9339
    subscriptions:
      - intf-config
    outputs:
      - file01

outputs:
  file01:
    type: file
    filename: /outputs/output.txt
    format: json

subscriptions:
  intf-config:
    prefix: "rfc7951:/Cisco-IOS-XE-interfaces-oper:interfaces/interface"
    stream-mode: sample
    sample-interval: 1m
    paths:
      - "rfc7951:/Cisco-IOS-XE-interfaces-oper:interfaces/interface/ipv4"

```
