### ISSUE TITLE
event-ieeefloat32 is working with gnmic processor command but not with subscribe

### ISSUE THREAD

**Issue by PatBoEPFL** [openconfig/gnmic#613]
Hello,

I'm using gnmic to collect metrics of Dell Enterprise SONiC switches (version 4.2.1 and 4.4.1). I've installed the latest gnmic version, 0.40.0, in order to use the event-ieeefloat32 to decode the PSU metrics (note: temperature probes and fan probes are not base64 encoded, but all PSU float type metrics are).

Here is the my config YAML file:

```yaml
username: "${GNMI_USERNAME}"
password: "${GNMI_PASSWORD}"
skip-verify: true

processors:
  extract_tags_from_switch:
    event-extract-tags:
      tags:
        - "${SW_FQDN_PARSING_REGEX}"
        
  convert_tag_infra:
    event-add-tag:
      tag-names:
        - 'infra'
      values:
        - 't'
      overwrite: true
      add:
        infra: 'test' 

  convert_values_by_dict:
    event-starlark:
      source: |
        val_map = {
          "UP": 1,
          "DOWN": 0,
          "ACTIVE": 1,
          "INACTIVE": 0,
        }

        def apply(*events):
          for e in events:
            for k, v in e.values.items():
              if v in val_map:
                e.values[k] = val_map[v]
          return events
      debug: true

  convert_encoded_float:
    event-ieeefloat32:
      value-names:
        - ".*state/input-current$"
        - ".*state/input-power$"
        - ".*state/input-voltage$"
        - ".*state/output-current$"
        - ".*state/output-power$"
        - ".*state/output-voltage$"
        - "/openconfig-platform:components/component/power-supply/state/temperature"

  val_to_tag:
    event-to-tag:
      value-names:
        - ".*/description$"
        - ".*/name$"
        - ".*/type$"
        - ".*/enabled$"

  write_component_events:
    event-write:
      value-names:
        - ".*"
      dst: gnmic_write_output.out
      separator: "\n####################\n"
      indent: "  "

  group_event:
    event-group-by:
      source: "sw-t-in-s19-pod1-bf1.xaas.epfl.ch:8080"


  pipeline1:
    event-combine:
      processors:
        - name: group_event
        - name: convert_encoded_float
        - name: extract_tags_from_switch
        - name: convert_tag_infra
        - name: convert_values_by_dict
        - name: val_to_tag
        - name: write_component_events


outputs:
  output_file:
    # required
    type: file
    # filename to write telemetry data to.
    # will be ignored if `file-type` is set
    filename: "${HOME}/gnmic_test_output.txt"
    rotation:
      max-size: 100 # size in megabytes
      max-age: 30 # max age in days
      max-backups: 3 # maximum number of old files to store, not counting the current file
      compress: false # whether or not to enable compression
    event-processors:
     - pipeline1
```

```bash
$ gnmic --debug --encoding proto --format event --config ~/gnmic_test.yaml --address '<SW_FQDN>:8080' sub --path '/components/component[name=PSU 1]/power-supply/state'
```

The content of the output file `"${HOME}/gnmic_test_output.txt"` looks like:

```json
[
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-current": "PpmZmg=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-power": "QowAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-voltage": "Q2OzMw=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-current": "QKAAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-power": "QnAAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-voltage": "QUZmZg=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/power-type": "VOLT_AC"
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670096956676236,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/temperature": "QhwAAA=="
        }
    }
]
[
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/temperature": "QhwAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/power-type": "VOLT_AC"
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-voltage": "QUZmZg=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-power": "QnAAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/output-current": "QLAAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-voltage": "Q2TMzQ=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-power": "QowAAA=="
        }
    },
    {
        "name": "default-1740670638",
        "timestamp": 1740670116966887846,
        "tags": {
            "component_name": "PSU 1",
            "datacenter": "<DC>",
            "infra": "test",
            "pod": "<POD>",
            "rack": "<RACK>",
            "role": "<ROLE>",
            "source": "<SW_FQDN>:8080",
            "subscription-name": "default-1740670638"
        },
        "values": {
            "/openconfig-platform:components/component/power-supply/state/input-current": "PpmZmg=="
        }
    }
]
```

One can see that the new tags are effectively created by the processors, but the power-supply voltages, currents, powers values are still encoded...

The following command will decode the power-supply metrics:

```bash
gnmic --config gnmic_test.yaml processor --name pipeline1 --input ~/gnmic_test_output.txt > ~/gnmic_test_output_processed.txt
```

Here is the content of `~/gnmic_test_output_processed.txt`:

```json
[
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-current": 0.3
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-power": 70
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-voltage": 227.7
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-current": 5
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-power": 60
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-voltage": 12.4
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/power-type": "VOLT_AC"
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670096956676352,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/temperature": 39
    }
  }
]
[
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/temperature": 39
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/power-type": "VOLT_AC"
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-voltage": 12.4
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-power": 60
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/output-current": 5.5
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-voltage": 228.8
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-power": 70
    }
  },
  {
    "name": "default-1740670638",
    "timestamp": 1740670116966887936,
    "tags": {
      "component_name": "PSU 1",
      "datacenter": "<DC>",
      "infra": "test",
      "pod": "<POD>",
      "rack": "<RACK>",
      "role": "<ROLE>",
      "source": "<SW_FQDN>:8080",
      "subscription-name": "default-1740670638"
    },
    "values": {
      "/openconfig-platform:components/component/power-supply/state/input-current": 0.3
    }
  }
]
```
Is it possible to use the `event-ieeefloat32` with `gnmic subscribe` command  or we must absolutely use the `gnmic processor` command? Or how do the gNMIc config file needs to be setup to ensure the data is directly decode with subscription?

Thanks in advance for your kind support!

Best regards,
  Patrice

**Comment by karimra** [comment]
It should work with Subscribe. I will look into this.

**Comment by PatBoEPFL** [comment]
Hi Karimra,

Until now, I've used only gnmic as a single instance. But today, I could put in place the [1.gnmic-nats-gnmic-prometheus](https://github.com/openconfig/gnmic/tree/main/examples/deployments/3.pipelines/1.gnmic-nats-gnmic-prometheus) deployment example.

I've adapted the example to my needs and put a processor pipeline in the output of the gnmic-relay container. My hypothesis, was that it may mimic the gnmic processor command.
And, it actually did function. Here is the input voltage in Prometheus DB:
```
openconfig_platform_components_component_power_supply_state_input_voltage{component_name="PSU 1", , instance="gnmic-relay:9804", job="gnmic", source="<my_sonic_switch_fqdn>:8080", subscription_name="psu"}	228.8000030517578
openconfig_platform_components_component_power_supply_state_input_voltage{component_name="PSU 1", , instance="gnmic-relay:9804", job="gnmic", source="<my_sonic_switch_fqdn>:8080", subscription_name="psu"}	228.8000030517578
```

So I've got a workaround with the pipeline deployement of gNMIc.

Best regards,
   Patrice

**Comment by PatBoEPFL** [comment]
Hello,

For your information, I've seen the behavior with value replacement done with starlark.
I've declared the following processor:

```yaml
  convert_values_by_dict:
    event-starlark:
      source: |
        val_map = {
          "UP": 1,
          "DOWN": 0,
          "ACTIVE": 1,
          "INACTIVE": 0,
        }

        def apply(*events):
          for e in events:
            for k, v in e.values.items():
              if v in val_map:
                e.values[k] = val_map[v]
          return events
```

If used in a single gnmic container instance, it won't work. But if used by gnmic-relay container as defined in the examples. It works.

This was done on version 0.40.0.

Best regards,
  Patrice
