### ISSUE TITLE
Add option to convert enum to numerical when possible

### ISSUE THREAD

**Issue by XioNoX** [openconfig/gnmic#631]
Hi,

We use gNMIc in subscribe mode to expose network devices metrics to Prometheus.
You can see our config in https://github.com/wikimedia/operations-puppet/blob/production/hieradata/common/profile/gnmi_telemetry.yaml

However as we're exposing that data for a timeseries DB, we need to do some transformations, especially some enums that we need to have as digits instead of strings. A good example is BGP session states : 

```
  rename-bgp-session-state:
    event-strings:
      value-names: ["/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state"]
      transforms:
        - replace: {apply-on: "value", old: "IDLE", new: "1"}
        - replace: {apply-on: "value", old: "CONNECT", new: "2"}
        - replace: {apply-on: "value", old: "ACTIVE", new: "3"}
        - replace: {apply-on: "value", old: "OPENSENT", new: "4"}
        - replace: {apply-on: "value", old: "OPENCONFIRM", new: "5"}
        - replace: {apply-on: "value", old: "ESTABLISHED", new: "6"}
```

The issue is that the YANG model doesn't seem to have a mapping from string to value. https://github.com/openconfig/public/blob/master/release/models/bgp/openconfig-bgp-neighbor.yang#L302

However some other models seems to have them, for example `bfd-diagnostic-code` does have `value X` https://github.com/openconfig/public/blob/master/release/models/bfd/openconfig-bfd.yang#L157 

As we're using gNMIc for more and more metrics (BGP, BFD, OSPF, etc), I was wondering if it was possible to add a way to use the numerical values when present it YANG. For example a processor dedicated to it.

And I'm wondering what it would take to define them in YANG for all the missing enums.

Thanks
