### ISSUE TITLE
drop or allow processors produce empty event slice

### ISSUE THREAD

**Issue by JerradGit** [openconfig/gnmic#71]
When using a processor such as drop or allow, it emits empty slices for events which match the condition.  

**Expected behaviour**: Events which are empty shouldn't be sent to outputs

I cloned the repo and did a `go mod tidy ; go build` from main and tested to ensure https://github.com/openconfig/gnmic/pull/61 was included.  I was able to confirm that empty maps are no longer showing up with this latest build, however the empty slice remains.

Let me know if you require more info, I am happy to build from a dev branch to test.

## with commented out allow processor

`gnmic --config reproduce.yml sub`
```yaml

---
port: 50051
targets:
  10.232.185.12:
    name: example_junos_device
    insecure: true
    skip-verify: true
    subscriptions:
      - physical_interfaces
    outputs:
      - stdout
outputs:
  stdout:
    type: file
    file-type: stdout
    format: event
    event-processors:
      - interface-group
    #!   - allow-example

processors:
  interface-group:
    event-group-by:
      tags:
        - source
        - subscription-name
        - interface_name
  allow-example:
    event-allow:
      condition: '.tags.interface_name == "xe-4/1/0"'

subscriptions:
  physical_interfaces:
    paths:
      - /interfaces/interface[name=xe-4/1/0]/state/counters
      - /interfaces/interface[name=xe-4/1/1]/state/counters
    stream-mode: SAMPLE
    mode: stream
    encoding: PROTO

```

```shell 
[
  {
    "name": "physical_interfaces",
    "timestamp": 1678825121253000000,
    "tags": {
      "interface_name": "xe-4/1/0",
      "source": "example_junos_device",
      "subscription-name": "physical_interfaces"
    },
    "values": {
      "/interfaces/interface/init_time": 1655218074,
      "/interfaces/interface/state/counters/carrier-transitions": 3,
      "/interfaces/interface/state/counters/in-broadcast-pkts": 15979531,
      "/interfaces/interface/state/counters/in-multicast-pkts": 22770053,
      "/interfaces/interface/state/counters/in-octets": 7929788976078,
      "/interfaces/interface/state/counters/in-pkts": 18958486714,
      "/interfaces/interface/state/counters/in-unicast-pkts": 18922354198,
      "/interfaces/interface/state/counters/out-broadcast-pkts": 9787761,
      "/interfaces/interface/state/counters/out-multicast-pkts": 76305229,
      "/interfaces/interface/state/counters/out-octets": 10629111199515,
      "/interfaces/interface/state/counters/out-pkts": 22230775663,
      "/interfaces/interface/state/counters/out-unicast-pkts": 22014540064,
      "/interfaces/interface/state/high-speed": 10000,
      "/interfaces/interface/state/parent_ae_name": ""
    }
  }
]
[
  {
    "name": "physical_interfaces",
    "timestamp": 1678825123270000000,
    "tags": {
      "interface_name": "xe-4/1/1",
      "source": "example_junos_device",
      "subscription-name": "physical_interfaces"
    },
    "values": {
      "/interfaces/interface/init_time": 1655218075,
      "/interfaces/interface/state/counters/carrier-transitions": 1,
      "/interfaces/interface/state/counters/in-broadcast-pkts": 31381,
      "/interfaces/interface/state/counters/in-multicast-pkts": 9076873,
      "/interfaces/interface/state/counters/in-octets": 4336832372284,
      "/interfaces/interface/state/counters/in-pkts": 9474114045,
      "/interfaces/interface/state/counters/in-unicast-pkts": 9465006085,
      "/interfaces/interface/state/counters/out-broadcast-pkts": 15098464,
      "/interfaces/interface/state/counters/out-multicast-pkts": 9076245,
      "/interfaces/interface/state/counters/out-octets": 2423800201161,
      "/interfaces/interface/state/counters/out-pkts": 7871520067,
      "/interfaces/interface/state/counters/out-unicast-pkts": 7832503512,
      "/interfaces/interface/state/high-speed": 10000,
      "/interfaces/interface/state/parent_ae_name": ""
    }
  }
]
```

## with allow processor

`gnmic --config reproduce.yml sub`
```yaml
---
port: 50051
targets:
  10.232.185.12:
    name: example_junos_device
    insecure: true
    skip-verify: true
    subscriptions:
      - physical_interfaces
    outputs:
      - stdout
outputs:
  stdout:
    type: file
    file-type: stdout
    format: event
    event-processors:
      - interface-group
      - allow-example

processors:
  interface-group:
    event-group-by:
      tags:
        - source
        - subscription-name
        - interface_name
  allow-example:
    event-allow:
      condition: '.tags.interface_name == "xe-4/1/0"'

subscriptions:
  physical_interfaces:
    paths:
      - /interfaces/interface[name=xe-4/1/0]/state/counters
      - /interfaces/interface[name=xe-4/1/1]/state/counters
    stream-mode: SAMPLE
    mode: stream
    encoding: PROTO
```

```shell
[
  {
    "name": "physical_interfaces",
    "timestamp": 1678825389160000000,
    "tags": {
      "interface_name": "xe-4/1/0",
      "source": "example_junos_device",
      "subscription-name": "physical_interfaces"
    },
    "values": {
      "/interfaces/interface/init_time": 1655218074,
      "/interfaces/interface/state/counters/carrier-transitions": 3,
      "/interfaces/interface/state/counters/in-broadcast-pkts": 15979656,
      "/interfaces/interface/state/counters/in-multicast-pkts": 22770390,
      "/interfaces/interface/state/counters/in-octets": 7929854166625,
      "/interfaces/interface/state/counters/in-pkts": 18958678574,
      "/interfaces/interface/state/counters/in-unicast-pkts": 18922545404,
      "/interfaces/interface/state/counters/out-broadcast-pkts": 9787890,
      "/interfaces/interface/state/counters/out-multicast-pkts": 76306097,
      "/interfaces/interface/state/counters/out-octets": 10629239524576,
      "/interfaces/interface/state/counters/out-pkts": 22231104460,
      "/interfaces/interface/state/counters/out-unicast-pkts": 22014866110,
      "/interfaces/interface/state/high-speed": 10000,
      "/interfaces/interface/state/parent_ae_name": ""
    }
  }
]
[] <------ this 
```

On devices with many interfaces it becomes very noisy

```shell
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[
  {
    "name": "physical_interfaces",
    "timestamp": 1678826366707000000,
    "tags": {
      "interface_name": "xe-4/1/0",
      "source": "example_junos_device",
      "subscription-name": "physical_interfaces"
    },
    "values": {
      "/interfaces/interface/init_time": 1655218074,
      "/interfaces/interface/state/counters/carrier-transitions": 3,
      "/interfaces/interface/state/counters/in-broadcast-pkts": 15980213,
      "/interfaces/interface/state/counters/in-multicast-pkts": 22771626,
      "/interfaces/interface/state/counters/in-octets": 7930092097044,
      "/interfaces/interface/state/counters/in-pkts": 18959410297,
      "/interfaces/interface/state/counters/in-unicast-pkts": 18923274892,
      "/interfaces/interface/state/counters/out-broadcast-pkts": 9788335,
      "/interfaces/interface/state/counters/out-multicast-pkts": 76309254,
      "/interfaces/interface/state/counters/out-octets": 10629720929160,
      "/interfaces/interface/state/counters/out-pkts": 22232311635,
      "/interfaces/interface/state/counters/out-unicast-pkts": 22016064341,
      "/interfaces/interface/state/high-speed": 10000,
      "/interfaces/interface/state/parent_ae_name": ""
    }
  }
]
[]
[]
[]
[]
[]
[]
[]
[]
```
