### ISSUE TITLE
Using format proto to stdout causes panic

### ISSUE THREAD

**Issue by richardeaxon** [openconfig/gnmic#85]
Should not be allowed as per docs, but causes panic if you try:

```
outputs:
  output1:
    type: file # output type
    file-type: stdout # or stderr
    format: proto
```

Panic caused:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2cede70]

goroutine 62 [running]:
golang.org/x/sync/semaphore.(*Weighted).Acquire(0x0, {0x42276b8, 0xc0002d7940}, 0x1)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/semaphore/semaphore.go:41 +0x50
github.com/openconfig/gnmic/outputs/file.(*File).Write(0xc0000a0d20, {0x42276b8?, 0xc0002d7940?}, {0x41fb460?, 0xc0001f3f40}, 0x0?)
        /home/runner/work/gnmic/gnmic/outputs/file/file_output.go:216 +0x9a
github.com/openconfig/gnmic/app.(*App).Export.func2({0x423d4a0?, 0xc0000a0d20?})
        /home/runner/work/gnmic/gnmic/app/collector.go:171 +0x82
created by github.com/openconfig/gnmic/app.(*App).Export
        /home/runner/work/gnmic/gnmic/app/collector.go:169 +0x38d
```

**Comment by richardeaxon** [comment]
And using an invalid file-type also causes a panic:

```
outputs:
  output1:
    type: file # output type
      #file-type: stdout # or stderr
    file-type: zzz
    format: event
    event-processors:
      - sample-processor
```
