### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by richardeaxon** [openconfig/gnmic#90]
The extract tags processor example in the docs does not work https://gnmic.openconfig.net/user_guide/event_processors/event_extract_tags/

```
processors:
  # processor name
  sample-processor:
    # processor type
    event-extract-tags:
      value-names:
        - `/(\w+)/(?P<group>\w+)/(\w+)`
```

The regex contains backticks that throw an error

```
failed loading config file: While parsing config: yaml: line 48: found character that cannot start any token
Error: no subscriptions or inputs configuration found
```

Remove the backticks and it works.

Also can I suggest more examples for the feature. I am struggling to understand how it works.
