### ISSUE TITLE
subscription name per xpath

### ISSUE THREAD

**Issue by jrametta** [openconfig/gnmic#91]
I was wondering if it is possible to use event message name or subscription_name on a per xpath basis

I know I can do something like this...
```
subscriptions:
 ipv4-bgp-routes:
    paths:
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/bgp"
 ipv4-bgp-vpn-routes:
    paths:
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/bgp-vpn"
 ipv4-direct-routes:
    paths:
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/direct"
```

rather than this...
```
subscriptions:
  route-counts:
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/bgp"
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/bgp-vpn"
      - "/state/service/vprn[service-name=*]/route-table/unicast/ipv4/statistics/direct"
```

but wondering if there are negatives consequences to this as number of xpaths per router could be many.  For example I can see Active RPC count on SROS router is increased.

Any suggestions, basically I'm looking for a way to easily identify a metric name (perhaps in addition to using path-base processor to trim event value keys in response).

thanks!
